import time
A = (ord('A'))
B = (ord('B'))
C = (ord('C'))
D = (ord('D'))
E = (ord('E'))
F = (ord('F'))
G = (ord('G'))
H = (ord('H'))
I = (ord('I'))
J = (ord('J'))
K = (ord('K'))
L = (ord('L'))
M = (ord('M'))
N = (ord('N'))
O = (ord('O'))
P = (ord('P'))
Q = (ord('Q'))
R = (ord('R'))
S = (ord('S'))
T = (ord('T'))
U = (ord('U'))
V = (ord('V'))
W = (ord('W'))
X = (ord('X'))
Y = (ord('Y'))
Z = (ord('Z'))
print(T+H+E+Q+U+I+C+K+B+R+O+W+N+F+O+X+J+U+M+P+S+O+V+E+R+T+H+E+L+A+Z+Y+D+O+G)
start = time.time()
print('time :',(time.time()-start)*1000)
